import { Inter } from 'next/font/google'
import Head from 'next/head'
import Layout from '@/components/layout/Layout'
import LatestStories from '../homeItems/LatestStories'
import Movies from '../homeItems/Movies'
import Travel from '../homeItems/Travel'
import Pictures from '../homeItems/Pictures'
import Mission from '../homeItems/Mission'
import SingUp from '../homeItems/SingUp'
import { CardData } from '@/pages'
import { FC } from 'react'
import { ICard, ICardData } from '@/interfaces/card.interfaces'

const inter = Inter({ subsets: ['latin'] })

const Home: FC<CardData> = (card: ICardData) => {
    return (
        <>
            <Head>
                <title>Next-app</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <main className=" max-h-max mx-auto">
                    <LatestStories card={card} />
                    <Movies />
                    <Travel />
                    <Pictures />
                    <Mission />
                    <SingUp />
                </main>
            </Layout>
        </>
    )
}

export default Home;
